import { Link } from "react-router-dom"

function HomePage() {
    return (
        <div className="homepage">
            <div className="homepage-card">
                <img className="homepage-image" src="../src/assets/beers.png" />
                <Link to="/beers">
                    <h1 className="homepage-headline">All Beers</h1>
                </Link>
                <p className="homepage-description">
                    {/* Generated by ChatGPT */}
                    Embark on a sensory journey with our curated list of beers,
                    where each brew is a testament to craftsmanship and flavor innovation.
                    The "Cascade Citrus Pale Ale" tantalizes with a burst of zesty hops,
                    while the "Midnight Velvet Porter" weaves a rich tapestry of chocolate and coffee notes.
                    For a tropical escape, the "Paradise Pineapple Wheat" beckons with its sun-soaked sweetness.
                    Meanwhile, the "Spice Odyssey Saison" takes your taste buds on a thrilling ride with its exotic blend of spices.
                    Experience a touch of heat with the "Firebrand Chili Lager," a bold choice for the adventurous.
                    Finally, savor the "Golden Harvest IPA," a liquid celebration of hops and honey.
                    This diverse lineup promises a flavor for every palate, ensuring your beer adventure is nothing short of extraordinary.
                    Cheers to exploration in every sip!
                </p>
            </div>

            <div className="homepage-card">
                <img className="homepage-image" src="../src/assets/random-beer.png" />
                <Link to="/random-beer">
                    <h1 className="homepage-headline">Random Beer</h1>
                </Link>
                <p className="homepage-description">
                    {/* Generated by ChatGPT */}
                    Embarking on a beer adventure? Take a leap into the unknown with the thrill of choosing a random
                    brew from our carefully curated list. Close your eyes and let your intuition guide you to a serendipitous selection.
                    Will it be the crisp allure of a pale ale or the comforting depths of a stout? Perhaps a tropical wheat beer or a spicy
                    saison awaits your discovery. Each choice is a ticket to a unique flavor realm, a surprise waiting to unfold.
                    Embrace the spontaneity, relish the mystery, and toast to the joy of exploring the unexpected with every random beer pick.
                    Cheers to the delightful surprises that lie within each uncharted sip!
                </p>
            </div>

            <div className="homepage-card">
                <img className="homepage-image" src="../src/assets/new-beer.png" />
                <Link to="/new-beer">
                    <h1 className="homepage-headline">New Beer</h1>
                </Link>
                <p className="homepage-description">
                    {/* Generated by JaimeGPT ;) */}
                    Have a personal favorite that is not listed here? Feel free to add to our existing list of amazing beers so that others can discover and enjoy your
                    favourite beer!
                </p>
            </div>
        </div>
    )
}

export default HomePage
