export { default as Home } from './Home'
export { default as Navbar } from './NavBar'
export { default as Beers } from './Beers'
export { default as ListBeers } from './ListBeers'
export { default as RandomBeers } from './RandomBeers'
export { default as NewBeer } from './NewBeer'